%虽然欧拉梁不是很对，但其他方法也难弄，先run下
k=1
l=0.1
x=0;
w=0;
theta=0;
%diyi
xp=l
w1=-1/k*exp(-k*xp)-xp+1/k;
theta1=exp(-k*xp)-1;
w=w1+w;
theta=theta1+theta;
x=l+x;
%
w2=-1/k*exp(-k*xp)-xp+1/k;
theta2=exp(-k*xp)-1;
x=x+xp*cos(theta)-w2*sin(theta);
w=w+xp*sin(theta)+w2*cos(theta);
theta=theta2+theta;
%
w3=-1/k*exp(-k*xp)-xp+1/k;
theta3=exp(-k*xp)-1;
x=x+xp*cos(theta)-w3*sin(theta);
w=w+xp*sin(theta)+w3*cos(theta);
theta=theta3+theta;

